<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="FleetStudio-21" failures="2" tests="4" name="Test" time="21.619" errors="0" timestamp="2023-03-06T13:27:54 IST">
  <testcase classname="fleetwally.wally.LoginValidation" name="LoginApplication" time="0.535"/>
  <testcase classname="fleetwally.wally.LoginValidation" name="LoginErrorMessage" time="1.352"/>
  <testcase classname="fleetwally.wally.LoginValidation" name="LoginErrorMessage" time="1.363">
    <failure type="java.lang.AssertionError" message="expected [User does not exist.] but found [Incorrect Credentials. Please try again]">
      <![CDATA[java.lang.AssertionError: expected [User does not exist.] but found [Incorrect Credentials. Please try again]
at fleetwally.wally.LoginValidation.LoginErrorMessage(LoginValidation.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorMessage -->
  <testcase classname="fleetwally.wally.LoginValidation" name="LoginErrorMessage" time="1.321">
    <failure type="java.lang.AssertionError" message="expected [User does not exist.] but found [Incorrect Credentials. Please try again]">
      <![CDATA[java.lang.AssertionError: expected [User does not exist.] but found [Incorrect Credentials. Please try again]
at fleetwally.wally.LoginValidation.LoginErrorMessage(LoginValidation.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorMessage -->
</testsuite> <!-- Test -->
